# frozen_string_literal: true

require_relative 'test_helper'

# This test ensures that all documents (posts and pages) can be rendered
# under Jekyll's strict mode for Liquid. It helps catch undeclared variables
# in page content, which would otherwise only be found during a full site build
# with strict error handling enabled.
class StrictRenderingTest < Minitest::Test
  def setup
    original_stdout = $stdout.clone
    original_stderr = $stderr.clone
    $stdout.reopen(File::NULL, 'w')
    $stderr.reopen(File::NULL, 'w')

    begin
      config = Jekyll.configuration.dup
      config['plugin_log_level'] = 'error' # Suppress info/warn logs for this test
      @site = Jekyll::Site.new(config)

      @site.reset
      @site.read

      # Workaround for a suspected issue where the test environment pollutes the
      # site's list of converters with invalid objects. We ensure that only
      # valid converters are present before running generators.
      @site.converters.keep_if { |c| c.respond_to?(:matches) }

      @site.generate
    ensure
      $stdout.reopen(original_stdout)
      $stderr.reopen(original_stderr)
    end
  end

  # Iterates through all documents, rendering each one's content in a strict
  # Liquid context to catch any undefined variable errors.
  def test_all_documents_render_in_strict_mode
    documents = @site.pages + @site.documents
    failures = []
    # Files generated by external plugins that don't follow our strict rules
    excluded_files = ['feed.xml', 'feed/books.xml', 'sitemap.xml']

    documents.each do |doc|
      next if doc.path.include?('vendor/') # Skip vendored files
      next if excluded_files.include?(doc.relative_path) # Skip non-compliant plugin files

      begin
        render_document_content_in_strict_mode(doc)
      rescue Liquid::UndefinedVariable => e
        failures << "Strict rendering failed for '#{doc.relative_path}': #{e.message}"
      rescue StandardError => e
        failures << "An unexpected error occurred for '#{doc.relative_path}': #{e.class} - #{e.message}\n  " \
                    "Backtrace: #{e.backtrace.select { |line| line.include?('/workspace/') }.join("\n             ")}"
      end
    end

    assert failures.empty?, "Found Liquid rendering errors in strict mode:\n- #{failures.join("\n- ")}"
  end

  private

  # Renders a document's content using Jekyll's own renderer but with
  # Liquid's strict mode temporarily enabled. This ensures the full Jekyll
  # context is available, avoiding errors from a manually-created context.
  def render_document_content_in_strict_mode(doc)
    original_liquid_config = @site.config['liquid'].dup
    @site.config['liquid']['error_mode'] = 'strict'
    @site.config['liquid']['strict_variables'] = true

    renderer = Jekyll::Renderer.new(@site, doc, @site.site_payload)
    renderer.run
  ensure
    # Restore original config to avoid affecting other tests
    @site.config['liquid'] = original_liquid_config
  end
end
