# frozen_string_literal: true

require 'jekyll'
require_relative 'text_processing_utils'

# Strips book-link hover-preview markup from all rendered feed XML pages
# so hidden preview content never leaks into feed readers as inline text.
# This covers feeds generated by jekyll-feed (e.g. /feed/books.xml) that
# don't use the custom feed.xml override template.
Jekyll::Hooks.register :pages, :post_render do |page|
  next unless page.output_ext == '.xml'
  next unless page.output&.include?('<!--book-preview-->')

  page.output = Jekyll::Infrastructure::TextProcessingUtils.strip_link_previews(page.output)
end
