# frozen_string_literal: true

require 'jekyll'
require_relative 'text_processing_utils'

# Strips book-link and footnote hover-preview markup from all rendered feed
# XML pages so hidden preview content never leaks into feed readers as inline
# text. This covers feeds generated by jekyll-feed (e.g. /feed/books.xml)
# that don't use the custom feed.xml override template.
Jekyll::Hooks.register :pages, :post_render do |page|
  next unless page.output_ext == '.xml'

  utils = Jekyll::Infrastructure::TextProcessingUtils

  page.output = utils.strip_link_previews(page.output) if page.output&.include?(utils::PREVIEW_OPEN)
  page.output = utils.strip_footnote_previews(page.output) if page.output&.include?(utils::FOOTNOTE_PREVIEW_OPEN)
end
